Rj tabbed interface
jrzricardo/photogram-industrial pull request #5
Opened 2024-07-06 20:21 UTC by jrzricardo

2024-07-06 20:26 UTC, AdolfoNava commented on app/views/users/show.html.erb
> +        <%= link_to "Liked photos", liked_path(@user.username), class: "nav-link" %>
good job handling the class here first try :)

2024-07-06 20:29 UTC, AdolfoNava commented on app/views/users/show.html.erb
> +        <a class="nav-link" href="#">Followers</a>
probably would get asked to turn these a tags to link_to

2024-07-06 20:30 UTC, AdolfoNava commented on app/controllers/users_controller.rb
need the other methods for the 3 pages

2024-07-06 20:31 UTC, AdolfoNava commented on config/routes.rb
> +  get ":username" => "users#show", as: :user
Missing 3 other routes as mentioned above

2024-07-06 20:31 UTC, AdolfoNava requested changes
Refer to the notes

2024-07-06 20:37 UTC, AdolfoNava approved these changes
Looks good now

2024-07-08 14:18 UTC, rezahusain commented on config/routes.rb
> +  get ":username/following" => "users#following", as: :following
Really good naming consistency!

2024-07-08 14:19 UTC, rezahusain commented on app/views/users/followers.html.erb
> +        <%= render "users/user", user: user %>
Love that your keeping your code shorter by utilizing partial templates.

2024-07-08 14:21 UTC, rezahusain commented on app/controllers/comments_controller.rb
> +      params.require(:comment).permit(:author_id, :photo_id, :body, )
Don't know if the trailing comma at the end of body will break anything but just double check and make sure it doesn't.

2024-07-08 14:21 UTC, rezahusain approved these changes
Overall looks solid! Code is easy to read and concise.

2024-07-08 14:36 UTC, CarlosCastanedaDev approved these changes
Great job, Ricardo!

You can now merge these changes back to main.

2024-07-08 16:42 UTC, CodeX-y commented
@photo = Photo.find(params[:id])

This is line 63 in your photos controller and it is causing an error. See if you can fix this error.

2024-07-08 16:46 UTC, CodeX-y requested changes
Try going through your routes through the url. ..../alice should work. then double check that all the buttons on the profile page work.

2024-07-08 17:11 UTC, CodeX-y approved these changes
Everything looks good! All your bootstrap is in partials and routes look good.

2024-07-08 17:11 UTC, CodeX-y approved these changes

2024-07-08 17:18 UTC, merged